- id: 200
  key: satoshi
  currency: btc
  sort_order: 2
  min_confirm: 1
  max_confirm: 6
- id: 210
  key: litecoin
  currency: ltc
  sort_order: 3
  min_confirm: 1
  max_confirm: 6
- id: 220
  key: viacoin
  currency: via
  sort_order: 4
  min_confirm: 1
  max_confirm: 6
- id: 230
  key: darkcoin
  currency: drk
  sort_order: 5
  min_confirm: 1
  max_confirm: 6
- id: 240
  key: dogecoin
  currency: doge
  sort_order: 5
  min_confirm: 1
  max_confirm: 6


