- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 300
  key: litecoin
  currency: ltc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelLitecoin
- id: 500
  key: viacoin
  currency: via
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelViacoin
- id: 600
  key: darkcoin
  currency: drk
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelDarkcoin

